# source 'https://git.oschina.net/shannon/CocoaPods-Specs-mirror.git'
# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!
target 'TradingDiary' do

pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift3'
pod 'SwiftyJSON'
pod 'Alamofire'
pod 'RealmSwift'
pod 'Charts'
pod 'Charts/Realm'
pod 'Toaster'
pod 'Validator'
pod 'ObjectMapper'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end

end

